service:
  name: slt-helloworld
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name


custom:
  webpack:
    webpackConfig: ./webpack.config.cjs
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# functions:
#   hello:
#     handler: handler.helloj
#     events:
#       - http:
#           method: get
#           path: hello
#   helloPost:
#     handler: handler.helloWithMessage
#     events:
#       - http:
#           method: post
#           path: helloPost
